spring.application.name=backend

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/maquetas_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:molose}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true